name = "Rilipack"
author = "septechx"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "281ef8348f71380635779bb225f407f6b65fca9a232f91571f6d0dd21bf5eef7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "datapacks/"
