name = "Rilipack"
author = "septechx"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4102ec1e39d59aa56f03df058b025b02e0ad772dd877d2f7f6032f937aa80710"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
