name = "Rilipack"
author = "septechx"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e07615598584c5b1fe2d31c931f60beeeb345ea4ca16ed85912a16517e5e1106"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "datapacks/"
