// priority: 0

global.REMOVALS = {
  tfmg: [
    "aluminum_spool",
    "copper_spool",
    "potentiometer",
    "electromagnetic_coil",
    "unfinished_electromagnetic_coil",
    "electric_pump",
    "stator",
    "rotor",
    "generator",
    "electric_motor",
    "voltmeter",
    "magnet",
    "polarizer",
    "transformer",
    "electric_diode",
    "voltage_observer",
    "traffic_light",
    "segmented_display",
    "cable_connector",
    "glass_cable_insulator",
    "copycat_cable_block",
    "brass_cable_hub",
    "copper_cable_hub",
    "steel_cable_hub",
    "aluminum_cable_hub",
    "steel_casing_cable_hub",
    "heavy_cable_hub",
    "cable_tube",
    "electric_post",
    "diagonal_cable_block",
    "accumulator",
    "light_bulb",
    "circular_light",
    "modern_light",
    "aluminum_lamp",
    "neon_tube",
    "electric_switch",
    "converter",
    "hardened_planks",
  ],
  createaddition: [
    "spool",
    "gold_spool",
    "festive_spool",
    "electrum_spool",
    "copper_spool",
    "portable_energy_interface",
    "electric_motor",
    "alternator",
    "tesla_coil",
    "connector",
    "small_light_connector",
    "large_connector",
    "redstone_relay",
    "modular_accumulator",
    "capacitor",
  ],
  createdieselgenerators: ["burner"],
  immersiveengineering: ["alloybrick", "thermoelectric_generator", "dynamo"],
  cyclic: [
    "crusher",
    "generator_solar",
    "battery_clay",
    "fluid_pipe",
    "item_pipe",
    "energy_pipe",
    "crafter",
    "battery",
    "melter",
    "solidifier",
    "packager",
    "generator_item",
    "generator_fluid",
    "generator_food",
    "generator_fuel",
    "wireless_fluid",
    "wireless_item",
    "wireless_energy",
    "peat_farm",
  ],
  rftoolspower: ["coalgenerator", "cell1", "cell2", "cell3"],
};

global.forEachItem = (map, f) => {
  Object.entries(map).forEach(([mod, items]) => {
    items.forEach((item) => {
      const ident = `${mod}:${item}`;
      f(ident);
    });
  });
};
