const REMOVALS = {
  immersiveengineering: [
    "blastfurnace/steel_block",
    "blastfurnace/steel",
    "crafting/treated_wood_horizontal",
    "crafting/rs_engineering",
    "crafting/component_steel",
    "crafting/component_iron",
    "crafting/heavy_engineering",
    "crafting/electrum_mix",
    "crafting/constantan_mix",
    "crafting/capacitor_lv",
    "crafting/capacitor_mv",
    "crafting/capacitor_hv",
    "blueprint/component_steel",
    "blueprint/component_iron",
  ],
  tfmg: [
    "industrial_blasting/steel",
    "industrial_blasting/steel_from_dust",
    "industrial_blasting/steel_from_raw_iron",
    "industrial_blasting/silicon",
    "vat_machine_recipe/arc_furnace_steel",
    "filling/hardened_planks",
    "crafting/kinetics/empty_circuit_board",
    "crafting/kinetics/fireproof_chemical_vat",
    "crafting/kinetics/steel_chemical_vat",
    "crafting/kinetics/cast_iron_chemical_vat",
    "sequenced_assembly/heavy_plate",
    "sequenced_assembly/steel_mechanism",
  ],
  jaopca: [
    "create.material_to_plate.plastic",
    "immersiveengineering.material_to_plate_hammer.plastic",
    "immersiveengineering.material_to_plate.plastic",
    "storage_blocks.to_material.obsidian",
  ],
  minecraft: ["enchanting_table"],
  quark: ["automation/crafting/obsidian_pressure_plate"],
  cyclic: ["disenchanter"],
  brewinandchewin: ["emptying/create/honey_bottle"],
  explorerscompass: ["explorers_compass"],
  xycraft_machines: [
    "compat/create/printed_silicon",
    "compat/create/printed_calculation",
    "compat/create/printed_engineering",
    "compat/create/printed_logic",
  ],
  laserio: ["logic_chip"],
  createdieselgenerators: ["compression_molding/blaze_rod"],
};

ServerEvents.recipes((e) => {
  global.forEachItem(REMOVALS, (ident) => e.remove({ id: ident }));
});
